# Generated by Django 4.2.5 on 2023-12-21 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'categoriaProducto', 'verbose_name_plural': 'categoriasProductos'},
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='updated',
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['nombre'], name='Tienda_cate_nombre_a28182_idx'),
        ),
    ]
