# Generated by Django 4.2.5 on 2023-12-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
