# Generated by Django 4.2.5 on 2023-11-01 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_comentario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
