# Generated by Django 4.2.5 on 2023-11-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_comentario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cuerpo',
            field=models.TextField(max_length=200),
        ),
    ]
