# Generated by Django 4.2.5 on 2023-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_comentario_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cuerpo',
            field=models.TextField(max_length=400),
        ),
    ]
