# Generated by Django 4.2.5 on 2023-12-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_comentario_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='categoria_post', to='Blog.categoria'),
        ),
    ]
